"use client";
import React from "react";
import { Provider } from "react-redux";
import { store } from "../store/Store";
import { Spinner } from "reactstrap";
import "@/styles/style.scss";
import Logo from "./(DashboardLayout)/layouts/logo/Logo";
import "@/app/api/index";

export const MyApp = ({ children }) => {
  return (
    <>
      <Provider store={store}>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,600&display=swap"
          rel="stylesheet"
        />
        <title>Monster Next Js 13.5.5 Admin Dashbaord</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* <Component {...pageProps} /> */}
        {children}
      </Provider>
    </>
  );
};

export default function RootLayout({ children }) {
  const [loading, setLoading] = React.useState(false);
  React.useEffect(() => {
    setTimeout(() => setLoading(true), 3000);
  }, []);
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider store={store}>
          {loading ? (
            // eslint-disable-next-line react/no-children-prop
            <MyApp children={children} />
          ) : (
            <div className="d-flex align-items-center justify-content-center h-100vh">
              <div className="text-center">
                <Spinner color="primary" className="mb-3">
                  Loading...
                </Spinner>
                <Logo />
              </div>
            </div>
          )}
        </Provider>
      </body>
    </html>
  );
}
